ALTER TABLE ZIPCODE_INFO
ADD STATE VARCHAR(2);

ALTER TABLE INSTRUCTOR_INFO
ADD STREET_ADDRESS VARCHAR(50), ZIP_CODE VARCHAR(5);

ALTER TABLE COURSE_INFO
ADD COURSE_NAME VARCHAR(50), COURSE_PREREQUISITE NUMERIC(8,0);

ALTER TABLE STUDENT_INFO
ADD STREET_ADDRESS VARCHAR(50), ZIP_CODE VARCHAR(5);

ALTER TABLE SECTION_INFO
ADD LOCATION VARCHAR(50), CAPACITY NUMERIC(3,0);

ALTER TABLE ENROLLMENT_INFO
ADD ENROLLMENT_DATE DATE;

ALTER TABLE GRADE_INFO
ADD NUMERIC_GRADE NUMERIC(3,0);